# coding: utf-8

"""
    CONTENT MANAGEMENT API

    CONTENT MANAGEMENT  # noqa: E501

    OpenAPI spec version: 0.1 beta
    Contact: some_email@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.delete_post_api import DeletePostApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDeletePostApi(unittest.TestCase):
    """DeletePostApi unit test stubs"""

    def setUp(self):
        self.api = api.delete_post_api.DeletePostApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_post(self):
        """Test case for delete_post

        Delete post  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
