# coding: utf-8

"""
    CONTENT MANAGEMENT API

    CONTENT MANAGEMENT  # noqa: E501

    OpenAPI spec version: 0.1 beta
    Contact: some_email@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.load_new_post_api import LoadNewPostApi  # noqa: E501
from swagger_client.rest import ApiException


class TestLoadNewPostApi(unittest.TestCase):
    """LoadNewPostApi unit test stubs"""

    def setUp(self):
        self.api = api.load_new_post_api.LoadNewPostApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_load_new_post(self):
        """Test case for load_new_post

        Loads a new post  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
