# coding: utf-8

"""
    CONTENT MANAGEMENT API

    CONTENT MANAGEMENT  # noqa: E501

    OpenAPI spec version: 0.1 beta
    Contact: some_email@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.successfull3 import Successfull3  # noqa: E501
from swagger_client.rest import ApiException


class TestSuccessfull3(unittest.TestCase):
    """Successfull3 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSuccessfull3(self):
        """Test Successfull3"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.successfull3.Successfull3()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
