# coding: utf-8

"""
    CONTENT MANAGEMENT API

    CONTENT MANAGEMENT  # noqa: E501

    OpenAPI spec version: 0.1 beta
    Contact: some_email@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.successfull1 import Successfull1  # noqa: E501
from swagger_client.rest import ApiException


class TestSuccessfull1(unittest.TestCase):
    """Successfull1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSuccessfull1(self):
        """Test Successfull1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.successfull1.Successfull1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
