# coding: utf-8

"""
    CONTENT MANAGEMENT API

    CONTENT MANAGEMENT  # noqa: E501

    OpenAPI spec version: 0.1 beta
    Contact: some_email@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.get_metadata_post_api import GetMetadataPostApi  # noqa: E501
from swagger_client.rest import ApiException


class TestGetMetadataPostApi(unittest.TestCase):
    """GetMetadataPostApi unit test stubs"""

    def setUp(self):
        self.api = api.get_metadata_post_api.GetMetadataPostApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_metadata_post(self):
        """Test case for get_metadata_post

        Get metadata post  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
