# coding: utf-8

"""
    CONTENT MANAGEMENT API

    CONTENT MANAGEMENT  # noqa: E501

    OpenAPI spec version: 0.1 beta
    Contact: some_email@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.successfull2 import Successfull2  # noqa: E501
from swagger_client.rest import ApiException


class TestSuccessfull2(unittest.TestCase):
    """Successfull2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSuccessfull2(self):
        """Test Successfull2"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.successfull2.Successfull2()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
