# coding: utf-8

"""
    CONTENT MANAGEMENT API

    CONTENT MANAGEMENT  # noqa: E501

    OpenAPI spec version: 0.1 beta
    Contact: some_email@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.edit_post_api import EditPostApi  # noqa: E501
from swagger_client.rest import ApiException


class TestEditPostApi(unittest.TestCase):
    """EditPostApi unit test stubs"""

    def setUp(self):
        self.api = api.edit_post_api.EditPostApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_edit_post(self):
        """Test case for edit_post

        Edit post  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
