version: "3.1"
services: 
    team2-app: 
        build: .
        ports: 
            - 8080:8080
        links: 
            - mongo
    mongo:
        image: mongo:latest
        ports:
            - 27017:27017
        restart: always
