# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Successfull1(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, atributes: List[str]=None, result: bool=None):  # noqa: E501
        """Successfull1 - a model defined in Swagger

        :param atributes: The atributes of this Successfull1.  # noqa: E501
        :type atributes: List[str]
        :param result: The result of this Successfull1.  # noqa: E501
        :type result: bool
        """
        self.swagger_types = {
            'atributes': List[str],
            'result': bool
        }

        self.attribute_map = {
            'atributes': 'Atributes',
            'result': 'Result'
        }
        self._atributes = atributes
        self._result = result

    @classmethod
    def from_dict(cls, dikt) -> 'Successfull1':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Successfull_1 of this Successfull1.  # noqa: E501
        :rtype: Successfull1
        """
        return util.deserialize_model(dikt, cls)

    @property
    def atributes(self) -> List[str]:
        """Gets the atributes of this Successfull1.


        :return: The atributes of this Successfull1.
        :rtype: List[str]
        """
        return self._atributes

    @atributes.setter
    def atributes(self, atributes: List[str]):
        """Sets the atributes of this Successfull1.


        :param atributes: The atributes of this Successfull1.
        :type atributes: List[str]
        """

        self._atributes = atributes

    @property
    def result(self) -> bool:
        """Gets the result of this Successfull1.


        :return: The result of this Successfull1.
        :rtype: bool
        """
        return self._result

    @result.setter
    def result(self, result: bool):
        """Sets the result of this Successfull1.


        :param result: The result of this Successfull1.
        :type result: bool
        """

        self._result = result
