# coding: utf-8

"""
    CONTENT MANAGEMENT API

    CONTENT MANAGEMENT  # noqa: E501

    OpenAPI spec version: 0.1 beta
    Contact: some_email@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class EditPostApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def edit_post(self, post_id, index_field, **kwargs):  # noqa: E501
        """Edit post  # noqa: E501

        You can change the post's atribute using it's index from GetPostAtributes  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.edit_post(post_id, index_field, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str post_id: Post id (required)
        :param int index_field: Index of the required field (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.edit_post_with_http_info(post_id, index_field, **kwargs)  # noqa: E501
        else:
            (data) = self.edit_post_with_http_info(post_id, index_field, **kwargs)  # noqa: E501
            return data

    def edit_post_with_http_info(self, post_id, index_field, **kwargs):  # noqa: E501
        """Edit post  # noqa: E501

        You can change the post's atribute using it's index from GetPostAtributes  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.edit_post_with_http_info(post_id, index_field, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str post_id: Post id (required)
        :param int index_field: Index of the required field (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['post_id', 'index_field']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method edit_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'post_id' is set
        if ('post_id' not in params or
                params['post_id'] is None):
            raise ValueError("Missing the required parameter `post_id` when calling `edit_post`")  # noqa: E501
        # verify the required parameter 'index_field' is set
        if ('index_field' not in params or
                params['index_field'] is None):
            raise ValueError("Missing the required parameter `index_field` when calling `edit_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'post_id' in params:
            query_params.append(('Post_ID', params['post_id']))  # noqa: E501
        if 'index_field' in params:
            query_params.append(('Index field', params['index_field']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/Edit_post_field', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
